---
- name: install and prepare PostgreSQL database
  yum:
    name={{item}}
    state=installed
    update_cache=yes
  with_items:
    - postgresql-server
    - python-psycopg2

- name: check if PostgreSQL database is initialized
  stat:
    path: /var/lib/pgsql/data/base
  register: pgdata_dir

- name: ensure PostgreSQL database is initialized
  command: "postgresql-setup initdb"
  when: not pgdata_dir.stat.exists
  become: yes
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true

- name: ensure PostgreSQL is started and enabled on boot
  service:
    name: postgresql
    state: started
    enabled: yes

- name: ensure database is created
  become: yes
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  become: yes
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db={{dbname}}
    name={{dbuser}}
    password={{dbpassword}}
    priv=ALL
