---
- name: install supervisord
  yum:
    name: supervisor
    update_cache: "yes"

- name: copy supervisord configuration for java app
  template: src=javaapp.conf dest=/etc/supervisord.d/javaapp.ini
  notify: supervisorctl update

- name: enable supervisord service
  service:
    name: supervisord
    enabled: "yes"
    state: started
